### ISSUE TITLE
Menu fucks up on game window resize

### ISSUE THREAD

**Issue by L1Q** [robotboy655/gmod-lua-menu#3] opened 2015-04-22 07:55 UTC
Unlike the original main menu this one appears unusable after the game window size (or resolution) was changed.

**Comment by robotboy655** [comment] 2015-04-22 09:14
Yeah, I am aware of the problem, it is caused by fonts being deleted on resolution change, more of a GMod bug.

**Comment by robotboy655** [comment] 2015-04-22 16:47
Will be fixed in the next GMod update.

**Closed by robotboy655** 2015-04-22 16:47 UTC
