### ISSUE TITLE
Dupes not working

### ISSUE THREAD

**Issue by elizabethlink1245** [robotboy655/gmod-lua-menu#36] opened 2022-09-11 03:41 UTC
im attempting to spawn dupes into the game however even if they are saved in my gmod's folder they won't load in the dupe menu in game

**Comment by robotboy655** [comment] 2022-09-11 12:19
Duplicate of https://github.com/robotboy655/gmod-lua-menu/issues/29

**Closed by robotboy655** 2022-09-11 12:19 UTC

**Comment by SpaceN64** [comment] 2024-01-02 08:19
found out whats wrong, basically what you want to do is get rid of the "-nochromium". the game will launch, and the dupe and saves menu will show.
