### ISSUE TITLE
Can't browse any Dupes or Saves

### ISSUE THREAD

**Issue by kor4yg** [robotboy655/gmod-lua-menu#43] opened 2023-01-20 08:59 UTC
Saves or Dupes are not displayed. The Saves and Dupes menus are completely blank.

**Comment by robotboy655** [comment] 2023-01-20 14:15
Duplicate of https://github.com/robotboy655/gmod-lua-menu/issues/29

**Closed by robotboy655** 2023-01-20 14:15 UTC

**Comment by SpaceN64** [comment] 2024-01-02 08:19
found out whats wrong, basically what you want to do is get rid of the "-nochromium". the game will launch, and the dupe and saves menu will show.
