### ISSUE TITLE
Blue Screen on MacOS

### ISSUE THREAD

**Issue by jadenquinn** [robotboy655/gmod-lua-menu#35] opened 2022-08-26 07:36 UTC
When I use this, it doesn't fix anything, it just gives me a totally blue screen on startup.

**Comment by robotboy655** [comment] 2022-08-26 12:59
Duplicate of https://github.com/robotboy655/gmod-lua-menu/issues/26

You most likely installed it incorrectly. 

It's also not a  "fix anything" project, it simply replaces the main menu with a different one.

**Closed by robotboy655** 2022-08-26 12:59 UTC
