### ISSUE TITLE
The menu isn't appearing

### ISSUE THREAD

**Issue by BandyRocket** [robotboy655/gmod-lua-menu#24] opened 2022-01-03 18:19 UTC
When I follow the instructions that were posted the menu isn't working for me. I'm on the latest version of Macos.

**Comment by robotboy655** [comment] 2022-01-03 18:26
Duplicate of https://github.com/robotboy655/gmod-lua-menu/issues/23

Please provide any information that might be useful if you wish to receive help.

**Closed by robotboy655** 2022-01-03 18:26 UTC
